server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 786238776
    url: jdbc:mysql://localhost:3306/ips?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.mouse.ips.pojo  # 别名
  mapper-locations: classpath:/mapper/*.xml # xml映射文件
logging:
  file:
    name: log/log.log
  level:
    root: info
    com: debug
